import java.util.Random;
import java.util.Scanner;

public class GenerateRandomNumbersAndStrings {

	public static void main(String[] args) {
		
		System.out.println("This is generated by using math.random which gives " +  Math.random()); 
		
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter number");
		int xyz = sc.nextInt();
		System.out.println("The number you entered is " + xyz);
		
		Random r = new Random();
		int rand = r.nextInt(100);
		System.out.println("The random number generated is " + rand);
		
		if(xyz>rand) {
			System.out.println("You are a winner");
		}else {
			System.out.println("Loser");
		}
		
		sc.close();
		
	}

}
